
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - edition-bohemica
    volumes:
      - type: bind
        source: ./server/uploads
        target: /usr/src/app/server/uploads

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:2.6.12
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Caban0ss!
    ports:
      - "27017:27017"
    volumes:
      - /var/edition-bohemica-dump:/dump
      - db-volume:/data
    networks:
      - edition-bohemica

volumes:
  db-volume:
    external: true
  uploads-volume:
    external: true

networks:
  edition-bohemica:
    external: true
