name: Hetzner Deployment
on: [push, pull_request]
jobs:
  deploy:
    name: "Deploy to Hetzner Server"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/hetzner.key
          chmod 600 ~/.ssh/hetzner.key
          cat >>~/.ssh/config <<END
          Host hetzner
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/hetzner.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: Check out the source
        run: ssh hetzner 'cd /root/deployments/edition-bohemica && git fetch && git reset --hard origin/master'

      - name: Stop old server and build new image
        run: ssh hetzner 'cd /root/deployments/edition-bohemica && docker compose down app && docker compose build app --no-cache'

      - name: Start the server
        if: ${{ always() }}
        run: ssh hetzner 'cd /root/deployments/edition-bohemica && docker compose up -d'
